version: '3.8'

services:
  web:
    build: .
    user: "appuser"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"  # Gunicorn will be accessed via Nginx; no direct external access
    env_file:
      - .env
    environment:
      - DJANGO_ENVIRONMENT=${DJANGO_ENVIRONMENT:-production}  # Provide default value
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost}

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      
volumes:
  static_volume:
  media_volume:

